### ISSUE TITLE
BUG: MagSafe light does not turn on after wake up from sleep

### ISSUE THREAD

**Issue by utkuonursahin** [charlie0129/batt#23]
To regenerate the issue follow these steps;
1. Put the Mac into sleep
2. Right before sleeping, Mac stops charging which is expected behavior
3. Wake up Mac
4. It uses the power from the wall but the MagSafe light doesn't lighting neither orange nor green. It is like closed even though Mac uses the power from the adapter at that time.

Is this a bug specific to my case or is it general bug? 

Are there any possible fixes soon?

Thanks for the great work!

**Comment by charlie0129** [comment]
After 4, if you wait for 5 minutes, does it make a difference?

**Comment by utkuonursahin** [comment]
Not it didn't help unfortunately.

**Comment by charlie0129** [comment]
Can you add the log from `/tmp/batt.log` to help identify the issue? If the file is too big can truncate it.

**Comment by charlie0129** [comment]
BTW: are you using v0.3.2? This is a known issue in v0.3.2, which is fixed in v0.3.3

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/4139131c-e6b0-4d28-b86e-2b905f88a37b" />

**Comment by utkuonursahin** [comment]
Yes I keep getting it in v0.3.3

**Comment by charlie0129** [comment]
Can you attach the log file from `/tmp/batt.log`? Otherwise I am not able to see what's going on.

**Comment by utkuonursahin** [comment]
I appreciate your effort, however it did not solve my problem unfortunately. Thanks for the trying but I decided not to use an app to control the battery.

**Comment by charlie0129** [comment]
Thanks for reporting.

I think this bug is resolved so I am going to close this issue. If anyone is still experiencing this bug, full free to comment or open a new issue.
